const PATH = '../assets/Images/';

const colors = {
  primary: '#673580',
  purpleSplash: '#E6A1BE',
  dropDownItemBackground: '#E3A9F3',
  white: '#FFFFFF',
  milkWhite: '#F2F2F2',
  wineRed: '#D74E79',
  black: '#000000',
  placeholderColor: '#9c9797',
  childPrimaryColor: '#D74E79',
  buttonColor: '#E3A9F3',
  greenBrand: '#30C4AE',
  brandYellow: '#F5A623',
  brandBlue: '#4A90E2',
};

const images = {
  bean: require(`${PATH}bean.png`),
  tradeMark: require(`${PATH}trademark.png`),
  parentBean: require(`${PATH}parentbean.png`),
  pregMom: require(`${PATH}pregMom.png`),
  tradeMarkParent: require(`${PATH}tradeMarkParent.png`),
  nextIcon: require(`${PATH}nexticon.png`),
  secondAuthImage: require(`${PATH}Group2.png`),
  thirdAuthImage: require(`${PATH}8.png`),
  fourthAuthImage: require(`${PATH}Group5.png`),
  eyeIcon: require(`${PATH}eye.png`),
  activeIcon: require(`${PATH}active.png`),
  primaryAuthBackground: require(`${PATH}1.png`),
  whiteLogo: require(`${PATH}whiteLogo.png`),
  whiteTradeMark: require(`${PATH}whiteTrade.png`),
  childbackground: require(`${PATH}group8.png`),
  childTrade: require(`${PATH}childtrade.png`),
  childBean: require(`${PATH}childbean.png`),
  childWelcomeScreenOne: require(`${PATH}childw1.png`),
  childWelcomeScreenTwo: require(`${PATH}childw2.png`),
  childWelcomeScreenThree: require(`${PATH}4.png`),
  HomeIcon: require(`${PATH}home.svg`),
  plusIcon: require(`${PATH}plus.png`),
  createTrust: require(`${PATH}Group-343.png`),
  setPersonalGoal: require(`${PATH}Group-342.png`),
  swipeImage: require(`${PATH}swipe.png`),
  drawer: require(`${PATH}drawerIcon.png`),
  notification: require(`${PATH}Notification.png`),
  backWardIcon: require(`${PATH}backwardIcon.png`),
  trustImage: require(`${PATH}Group-3445.png`),
  topUPImage: require(`${PATH}Group-3446.png`),
  userAvater: require(`${PATH}blackgal.png`),
  masterCard: require(`${PATH}mastercard.png`),
  forward: require(`${PATH}forward.png`),
  tick: require(`${PATH}tick.png`),
};

export {colors, images};
